language: ruby

rvm:
  - 2.3.3

sudo: required

secure: "Z0PPkIPMlOUg8iIZsF+cKFwCRIp6a5wVPpf2YekiQdj0RUNrXCKGX9k8QRFnZeGdgb3GaTywGe6YELDWkoxDqzlkvUObNSu5+7pldcx507N0Y7LifvhIm3ooSM/TJysjkrsHUQDjtExwa0W+eOK/aKm0CzxxpBsJ1nDyGNCaRdKGcPWqlAms1IlSuoqGKtpmIt2jmcyqglOOGd4AcAKrYGI1kBopR8YLql/C3JQORzIqCfH4n4CK+uza7ouLh8teppO3O6NmwmVQR57dr/RDZbWB3osPkxqLdF8q2ZZZXY+p9VuU7V5aGr1yfvhCLO3ZmOggHKwlfeEL+TSbdDGU01QHAnsjoWW+Z2mr/ngDHc9/Js4P4jqkErTLDJ+MyCuLvyMROAW1dVLsDA1tTAOfe8JmcemMv2MR9JtFW5XY6gXfu4KJhLauCwKowREbYHSjN7tqRQEb8YtrYcNIGAoaX6Iw//O8oMB8//JOP61DlgbSCZdPT19/BqJzUy7WUHwJCGYBZcdzCT/xrwhFnZdiQy3rUhesgE9trybpH4+o4o1JM8KBoXN2dEF6ydkswhMR/FiTd47KnLkbYbAMmM2oKzKQwORDf085sHhmLk0pJvve8b7YIsYFk4c4JUQKX0Vf3W0h0YgqZ5FukjrXLB+qQVkjAKMDX7b0WUkqoMcyuNM="

script: bundle exec rspec spec
