language: ruby

rvm:
  - 2.3.3

sudo: required

secure: "Ji1YuiYNJoKN+BU1EtdTyQYIFVQRHrGt0wSDeus6sEqN+JC2sMFRFYAG/laoRKpsU23xmW7TYyscYw0RefirwGu+dKYb3jekTs3N3eCFNHn13chAmowK2VOpzAlG9SSpz0e8lkxzHOiJ+RmEuCGEr3kKizEyJB9Ysggt07QP1ne6blGB+GGVqN39dQPDjCg+bv/2MjvvgXOU/dzDpRuKEalYEnSNcmm5IDFKtLvUst0gjsSdze1cV36MTtOtCXKF/ADl6s97xqaCXpj5f+1lVeJNBhHaGB8C5whZxU3qOY9ZeydZNFzXdu1QNTZCrE0JcUR6MuYRjlWz9EUG0GpX2+6mTLgpkrMKcHrGj+cyDoszJM6VzakNqM7M7pu2ccEJoOvgbXQQuQG7d+IxW7un8ossHHfKd4cbXnQEgeIyqW4Dnv61ep31nm9lAAVsYkL/Etj8LIeKAjYB4642DCObMcDDr+mmqtAWEafO7Y/zMMs3Qm9wkYR7Q+OvNFvLL9TlgkJEhovZG3qeFpdSudaQaN+F2Z6CjNC5Ua5ED905+IeC5wKJgBSNPztizCGmMBcxl71bReQL9hNsvYSzkBVze5Rrf8JYpa6G/eiHtRcamsYKWzdmTVLrM+/qdMs7+EkI4N4XaHSMFEfV0w17FUsfyzGJbnbGLmlBGXrvvIe85LM="

script: bundle exec rspec spec
