toolbar:
  - italic
menubar: false
selector: 'textarea'
height: 275
force_p_newlines : false
forced_root_block : ""
setup: function(ed) {
    ed.on('init', function()
    {
      this.getDoc().body.style.fontSize = '16px';
    });
  }
